export const BACKEND_PATH = "https://auctionsystem-production.up.railway.app/"
export const USER_PATH = "https://auctionsystem-production.up.railway.app/api/users"
export const AUCTION_PATH = "https://auctionsystem-production.up.railway.app/api/auctions"
export const BID_PATH = "https://auctionsystem-production.up.railway.app/api/bids"
export const ADMIN_PATH = "https://auctionsystem-production.up.railway.app/api/admin"